manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: eternal_keypad_rgb
      import: app/west.yml
  self:
    path: config
